server:
  port: 8950
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

      routes:
        - id: news
          uri: lb://news
          predicates:
            - Path=/news/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**

        - id: admin
          uri: lb://user
          predicates:
            - Path=/admin/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://42.192.40.227:8915/eureka

